options:
  version:
    type: string
    default: "0.90.7"
    description: |
      This sets the elasticsearch version number that will be used.
      If you're going to plug in logstash,  make sure versions match.
  apt-repository:
    type: string
    default: "deb http://packages.elasticsearch.org/elasticsearch/1.0/debian stable main"
    description: |
      A deb-line for an extra apt archive to add to the system during install.
  cluster-name:
    type: string
    default: "elasticsearch"
    description: |
      This sets the elasticsearch cluster name, which is used to discover
      and auto-join other nodes. don not change this if you want
      elasticsearch and kibana to work.
  install-ansible-from-ppa:
    type: boolean
    default: true
    description: |
      By default ansible will be installed from the Ansible ppa. You can
      set this to false for your deployments if you have ansible available
