options:
  version:
    type: string
    default: "0.19.2"
    description: |
      This sets the elasticsearch version number that will be used.
  cluster-name:
    type: string
    default: "elasticsearch"
    description: |
      This sets the elasticsearch cluster name, which is used to discover and auto-join other nodes.
  access-key:
    type: string
    description: |
      Access key for EC2.
  secret-key:
    type: string
    description: |
      Secret key for EC2.
  region:
    type: string
    default: "us-east"
    description: |
      This sets the region that will be used for discovery on ec2
  bucket-name:
    type: string
    description: |
      This sets the s3 bucket name for the elasticsearch s3 gateway.