options:
  version:
    type: string
    default: "0.90.7"
    description: |
      This sets the elasticsearch version number that will be used.
      If you're going to plug in logstash,  make sure versions match.
  downloadurl:
    type: string
    default: "https://download.elasticsearch.org/elasticsearch/elasticsearch"
    description: |
      URL from which to download elasticsearch.
  checksum:
    type: string
    default: "a3ec3c05ffabf8048642aa431b675f3c132b4fae755e1b7aee0cb9fe3f2a37ba"
    description: |
      SHA256 checksum of elasticsearch download.
  archive-package-name:
    type: string
    default: ""
    description: |
        By default, the elasticsearch deb package will be downloaded from the
        above url, but if you specify an archive-package-name, the charm
        will instead install the given package. You will need to ensure
        that the package is available in any archives you have available.
  cluster-name:
    type: string
    default: "elasticsearch"
    description: |
      This sets the elasticsearch cluster name, which is used to discover
      and auto-join other nodes. don not change this if you want
      elasticsearch and kibana to work.
  install-ansible-from-ppa:
    type: boolean
    default: true
    description: |
      By default ansible will be installed from the Ansible ppa. You can
      set this to false for your deployments if you have ansible available
