options:
  apt-repository:
    type: string
    default: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
    description: |
      A deb-line for the apt archive which contains the elasticsearch package.
      This is necessary until elasticsearch gets into the debian/ubuntu archives.
  apt-key-url:
    type: string
    default: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    description: |
      The url for the key for the apt-repository.
  es-heap-size:
    type: int
    default: 3
    description: |
      Maximum and initial JVM heap size for Elasticsearch, in GB
  gpg-key-id:
    type: string
    default: D88E42B4
    description: |
      Elasticsearch's GPG fingerprint to validate the apt key
  gpg-key:
    type: string
    default: ""
    description: |
      ES repository key to use. This option can be used instead of
      apt-key-url and gpg-key in environments where proxy servers
      block access to apt-key-url.
  cluster-name:
    type: string
    default: "elasticsearch"
    description: |
      This sets the elasticsearch cluster name.
  firewall_enabled:
    type: boolean
    default: true
    description: |
      By default, the admin and peer ports (9200 and 9300) are only accessible
      to clients and peers respectively. Switch this to false to enable access
      from any machine.
  nagios_context:
    type: string
    default: "juju"
    description: |
      Used by the nrpe-external-master subordinate charm.
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like:
      .
          juju-myservice-0
      .
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  nagios_servicegroups:
    type: string
    default: ""
    description: |
      A comma-separated list of nagios servicegroups.
      If left empty, the nagios_context will be used as the servicegroup.
