options:
  version:
    type: string
    default: "0.19.4"
    description: |
      This sets the elasticsearch version number that will be used.
  cluster-name:
    type: string
    default: "elasticsearch"
    description: |
      This sets the elasticsearch cluster name, which is used to discover and auto-join other nodes.
  bootstrap-class:
    type: string
    default: "org.elasticsearch.bootstrap.ElasticSearchF"
    description: |
      Class used by elasticsearch service wrapper, should be org.elasticsearch.bootstrap.ElasticSearch for versions
      less than or equal to 0.18.7
  access-key:
    type: string
    description: |
      Access key for EC2.
  secret-key:
    type: string
    description: |
      Secret key for EC2.
  region:
    type: string
    default: "us-east"
    description: |
      This sets the region that will be used for discovery on ec2
  bucket-name:
    type: string
    description: |
      This sets the s3 bucket name for the elasticsearch s3 gateway.