- hosts: localhost
  roles:
    - role: nrpe
      check_name: check_http
      check_params: -H localhost -u /_cluster/health -p 9200 -w 2 -c 3 -s green
      service_description: "Verify the cluster health is green."

  handlers:

    - name: Restart ElasticSearch
      service: name=elasticsearch state=restarted

  vars:
    - service_name: "{{ local_unit.split('/')[0] }}"

  tasks:

    - include: tasks/install-elasticsearch.yml
    - include: tasks/peer-relations.yml
    - include: tasks/setup-ufw.yml
      tags:
        - install
        - upgrade-charm
        - config-changed
        - client-relation-joined
        - client-relation-departed
        - peer-relation-joined
        - peer-relation-departed

    - name: Update elasticsearch.yml
      tags:
        - config-changed
      template: src={{ charm_dir }}/templates/elasticsearch.yml
                dest=/etc/elasticsearch/elasticsearch.yml
                mode=0644
                backup=yes
      notify:
        - Restart ElasticSearch

    - name: Update ES JVM configuration
      tags:
        - config-changed
      template: src={{ charm_dir }}/templates/jvm.options
                dest=/etc/elasticsearch/jvm.options
                mode=0644
                backup=yes
      notify:
        - Restart ElasticSearch

    - name: Open ES Port when exposed
      command: open-port 9200
      tags:
        - start

    - name: Start ElasticSearch
      service: name=elasticsearch state=started enabled=yes
      tags:
        - start

    - name: Stop ElasticSearch
      service: name=elasticsearch state=stopped
      tags:
        - stop

    - name: Get the ElasticSearch version
      tags:
        - install
        - upgrade-charm
        - client-relation-joined
      shell: apt-cache policy elasticsearch | grep -oe 'Installed:.*' | cut -d' ' -f2
      register: es_version

    - name: Set ElasticSearch version
      command: application-version-set {{ es_version.stdout }}
      tags:
        - install
        - upgrade-charm

    - name: Get the primary address of client relation
      tags:
        - client-relation-joined
      command: network-get client --primary-address
      register: client_primary_address

    - name: Relate the cluster name and host.
      tags:
        - client-relation-joined
      command: >
        relation-set
        cluster-name={{ cluster_name }}
        host={{ client_primary_address.stdout }}
        port=9200
        version={{ es_version.stdout }}

    - name: Relate logs
      tags:
        - logs-relation-joined
      command: >
        relation-set
        file=/var/log/elasticsearch/elasticsearch.log
        type=elasticsearch

    # A bug in the ansible hooks() helper requires at least
    # one task to be tagged.
    - name: Empty task to keep ansible helper satisfied.
      debug: msg="Noop ansible task."
      tags:
        - data-relation-joined
        - data-relation-changed
        - data-relation-departed
        - data-relation-broken

    # A bug in the ansible hooks() helper requires at least
    # one task to be tagged.
    - name: Set exit user messaging.
      command: >
        status-set
        active
        Ready
      tags:
        - client-relation-joined
        - client-relation-departed
        - peer-relation-joined
        - peer-relation-departed
        - start
