- hosts: localhost
  roles:
    - role: nrpe
      check_name: check_http
      check_params: -H localhost -u /_cluster/health -p 9200 -w 2 -c 3 -s green
      service_context: "{{ cluster_name }}"
      service_description: "Verify the cluster health is green."

  handlers:

    - name: Update configuration
      template: src={{ charm_dir }}/templates/elasticsearch.yml
                dest=/etc/elasticsearch/elasticsearch.yml
                mode=0644
                backup=yes

    - name: Restart ElasticSearch
      service: name=elasticsearch state=restarted

  tasks:

    - name: Add apt key.
      tags:
        - install
        - upgrade-charm
        - config-changed
      apt_key: url={{ apt_key_url }} state=present
      when: apt_key_url != ""

    - name: Add apt archive.
      tags:
        - install
        - upgrade-charm
        - config-changed
      apt_repository:
        repo: "{{ apt_repository }}"
        state: present
      when: apt_repository != ""

    - name: Install required packages.
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items:
        - openjdk-7-jre-headless
        - elasticsearch
      tags:
        - install
        - upgrade-charm

    # XXX Testing shows that currently peer-relation-joined is run
    # not just when the unit joins the peer relationship, but every
    # time a new unit is added to the peer relationship. ElasticSearch
    # needs to set the existing peer hosts only when first joining the
    # peer relationship.
    - name: Update config with peer hosts
      command: /usr/bin/touch {{ charm_dir }}/config-already-updated-with-peers creates={{ charm_dir }}/config-already-updated-with-peers
      tags:
        - peer-relation-joined
      notify:
        - Update configuration
        - Restart ElasticSearch

    - name: Start ElasticSearch
      service: name=elasticsearch state=started
      tags:
        - start

    - name: Stop ElasticSearch
      service: name=elasticsearch state=stopped
      tags:
        - stop

    - name: Relate the cluster name and host.
      # Provided for backwards compatability with existing charms
      # relating to elasticsearch (kibana, logstash-indexer).
      tags:
        - cluster-relation-joined
        - rest-relation-joined
      command: >
        relation-set
        cluster-name={{ cluster_name }}
        host={{ ansible_default_ipv4.address }}
