- hosts: localhost

  handlers:

    - name: Update configuration
      template: src={{ charm_dir }}/templates/elasticsearch.yml
                dest=/etc/elasticsearch/elasticsearch.yml
                mode=0644
                backup=yes

    - name: Restart ElasticSearch
      service: name=elasticsearch state=restarted

  tasks:

    - name: Install required packages.
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items:
        - openjdk-7-jre-headless
      tags:
        - install
        - upgrade-charm
      notify:
        - Restart ElasticSearch

    - name: Download ElasticSearch package if necessary.
      get_url: url={{ downloadurl }}/elasticsearch-{{ version }}.deb
               dest={{ charm_dir }}/files/elasticsearch-{{ version }}.deb
               sha256sum={{ checksum }}
      tags:
        - install
        - config-changed
      when: archive_package_name == ""

    - name: Install ElasticSearch
      command: dpkg -i {{ charm_dir }}/files/elasticsearch-{{ version }}.deb
               creates=/usr/share/elasticsearch/lib/elasticsearch-{{ version }}.jar
      tags:
        - install
        - config-changed
      notify:
        - Update configuration
        - Restart ElasticSearch
      when: archive_package_name == ""

    - name: Install archive elasticsearch package.
      apt: pkg={{ archive_package_name }} state=latest update_cache=yes
      tags:
        - install
        - upgrade-charm
      notify:
        - Update configuration
        - Restart ElasticSearch
      when: archive_package_name != ""

    # XXX Testing shows that currently peer-relation-joined is run
    # not just when the unit joins the peer relationship, but every
    # time a new unit is added to the peer relationship. ElasticSearch
    # needs to set the existing peer hosts only when first joining the
    # peer relationship.
    - name: Update config with peer hosts
      command: /usr/bin/touch {{ charm_dir }}/config-already-updated-with-peers creates={{ charm_dir }}/config-already-updated-with-peers
      tags:
        - peer-relation-joined
      notify:
        - Update configuration
        - Restart ElasticSearch

    - name: Start ElasticSearch
      service: name=elasticsearch state=started
      tags:
        - start

    - name: Stop ElasticSearch
      service: name=elasticsearch state=stopped
      tags:
        - stop
