- hosts: localhost
  roles:
    - role: nrpe
      check_name: check_http
      check_params: -H localhost -u /_cluster/health -p 9200 -w 2 -c 3 -s green
      service_description: "Verify the cluster health is green."

  handlers:

    - name: Restart ElasticSearch
      service: name=elasticsearch state=restarted

  tasks:

    - include: tasks/peer-relations.yml

    - name: Add apt key.
      tags:
        - install
        - upgrade-charm
        - config-changed
      apt_key: url={{ apt_key_url }} state=present
      when: apt_key_url != ""

    - name: Add apt archive.
      tags:
        - install
        - upgrade-charm
        - config-changed
      apt_repository:
        repo: "{{ apt_repository }}"
        state: present
      when: apt_repository != ""

    - name: Install required packages.
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items:
        - openjdk-7-jre-headless
        - elasticsearch
      tags:
        - install
        - upgrade-charm

    - name: Update configuration
      tags:
        - config-changed
      template: src={{ charm_dir }}/templates/elasticsearch.yml
                dest=/etc/elasticsearch/elasticsearch.yml
                mode=0644
                backup=yes
      notify:
        - Restart ElasticSearch

    - name: Start ElasticSearch
      service: name=elasticsearch state=started
      tags:
        - start

    - name: Stop ElasticSearch
      service: name=elasticsearch state=stopped
      tags:
        - stop

    - name: Relate the cluster name and host.
      # Provided for backwards compatability with existing charms
      # relating to elasticsearch (kibana, logstash-indexer).
      tags:
        - cluster-relation-joined
        - rest-relation-joined
      command: >
        relation-set
        cluster-name={{ cluster_name }}
        host={{ ansible_default_ipv4.address }}

    - name: Communicate website details
      # The default relation data includes private-address which is
      # already appropriately named, we just need to include the port.
      tags:
        - website-relation-changed
        - website-relation-joined
      command: >
        relation-set
        port=9200
