#!/usr/bin/python3
import amulet
import helpers


d = amulet.Deployment(series='trusty')

d.add('elasticsearch')

helpers.setup_deployment(d)

health = helpers.get_cluster_health(d)

if health['status'] not in ('green', 'yellow'):
    msg = "Elastic Search status is %s" % health['status']
    amulet.raise_status(amulet.FAIL, msg=msg)

# Create a test index.
curl_command = """
curl -XPUT 'http://localhost:9200/test/tweet/1' -d '{
    "user" : "me",
    "message" : "testing"
}'
"""
response = helpers.curl_on_unit(curl_command, d)

health = helpers.get_index_health(d, 'test')
if health['status'] not in ('green', 'yellow'):
    msg = "Elastic Search test index status is %s." % health['status']
    amulet.raise_status(amulet.FAIL, msg=msg)

print("Successfully created test index.")
