- name: Write nagios check_http command config.
  tags:
    - nrpe-external-master-relation-changed
  template:
    src: "check_http.cfg.jinja2"
    dest: "/etc/nagios/nrpe.d/check_http.cfg"
    owner: ubunet
    group: ubunet
    mode: 0644

- name: Write nagios check_http service definition.
  tags:
    - nrpe-external-master-relation-changed
  template:
    src: "check_http_service_definition.cfg.jinja2"
    dest: "/var/lib/nagios/export/service__juju-elasticsearch-0_check_http.cfg"
    owner: ubunet
    group: ubunet
    mode: 0644
